import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    'Installing',
    'Troubleshooting',
    'Configuration',
    {
      type: 'category',
      label: 'Rules',
      items: [
          'Rules/Intro',
          {
              type: 'category',
              label: 'Examples',
              items: [{ type: 'autogenerated', dirName: 'Rules/Examples' }],
          },
          {
              type: 'category',
              label: 'Effects',
              items: [{ type: 'autogenerated', dirName: 'Rules/Effects' }],
          },
          {
            type: 'category',
            label: 'Conditions',
            items: [{ type: 'autogenerated', dirName: 'Rules/Conditions' }],
          },
      ],
    },
    'API',
  ],
};

export default sidebars;
