name: Snapshot Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # Every day at 10:00 UTC

permissions:
  contents: read
  actions: read

jobs:
  check-recent-commits:
    runs-on: ubuntu-latest
    outputs:
      recent: ${{ steps.check.outputs.recent }}
      count: ${{ steps.check.outputs.count }}
    steps:
      - name: Check for commits in last 24h
        id: check
        env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SINCE=$(date -u -d '24 hours ago' '+%Y-%m-%dT%H:%M:%SZ')
          COUNT=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${GH_REPO}/commits?since=${SINCE}" \
            | jq 'length')
          echo "Commits in last 24h: ${COUNT}"
          echo "count=${COUNT}" >> "$GITHUB_OUTPUT"
          if [ "${COUNT}" -gt 0 ]; then
            echo "recent=true" >> "$GITHUB_OUTPUT"
          else
            echo "recent=false" >> "$GITHUB_OUTPUT"
          fi

  build-snapshot:
    name: Build Snapshot
    needs: check-recent-commits
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check-recent-commits.outputs.recent == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Generate snapshot version
        id: versioning
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          DATE=$(date +'%y%m%d') # Format: YYMMDD
          API_URL="https://api.github.com/repos/${REPO}/actions/artifacts"
          
          # Count matching snapshot builds for the current date
          BUILD_COUNT=$(curl -s -H "Authorization: Bearer $TOKEN" "$API_URL" \
            | jq "[.artifacts[] | select(.name | startswith(\"BetterKeepInventory-${BASE_VERSION}-SNAPSHOT-${DATE}\"))] | length")
          
          BUILD_COUNT=$((BUILD_COUNT + 1))
          VERSION="${BASE_VERSION}-SNAPSHOT-${DATE}${BUILD_COUNT}"
          
          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"


      - name: Apply version
        run: |
          mvn versions:set -DnewVersion=${{ steps.versioning.outputs.version }} -DgenerateBackupPoms=false

      - name: Build project
        run: mvn versions:update-child-modules clean compile package verify -DskipTests -f pom.xml

      - name: Rename JAR
        run: |
          mkdir out
          mv ./plugin/target/BetterKeepInventory-plugin-${{ steps.versioning.outputs.version }}-shaded.jar ./out/BetterKeepInventory-${{ steps.versioning.outputs.version }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterKeepInventory-${{ steps.versioning.outputs.version }}
          path: ./out/BetterKeepInventory-${{ steps.versioning.outputs.version }}.jar
